<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function ($) {
        $.validator.addMethod(
            'validation-validate-admin-password', function (v) {
                var pass;
                var regex = new RegExp("(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.{16,})(?=.*[$&+,:;=?@#|'<>.^*()%!-])");
                if (v === null) {
                    return false;
                }

                // Strip leading and trailing spaces
                pass = $.trim(v);

                if (pass.length === 0) {
                    return true;
                }

                if (!regex.test(v)) {
                    return false;
                }
                return true;
            },
            $.mage.__('Please enter 16 or more characters, using both numeric, min, maj and a special char.')
        );
    });
</script>